/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovindaDAO } from "./GovindaDAO";
export type { GovindaToken } from "./GovindaToken";
export type { Treasury } from "./Treasury";
