/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovindaDAO__factory } from "./GovindaDAO__factory";
export { GovindaToken__factory } from "./GovindaToken__factory";
export { Treasury__factory } from "./Treasury__factory";
